#!/bin/sh -ex

hwclock=`sysctl -n kern.timecounter.hardware`

if [ "$hwclock" = kvmclock ]; then
  exit 0
fi

plg=""

model=`sysctl -n hw.model`
if [ -z "${model##AMD *}" ]; then
  plg="os-cpu-microcode-amd"
elif [ -z "${model##Intel(R) *}" ]; then
  plg="os-cpu-microcode-intel"
fi

if [ -n "$plg" ]; then
  opnsense-api core/firmware/install/"$plg" '{}'
  st=unknown
  while [ "$st" != done ]; do
    sleep 3
    st=`opnsense-api core/firmware/upgradestatus | jq -r .status`
  done
fi
