#!/bin/sh -ex

. b4ck.subr

########################################################################
# https://$(hostname)/ui/firewall/alias

apply=false

if no_alias dns2tun; then
  opnsense-api firewall/alias/addItem/ '{"alias":{"name":"dns2tun","enabled":"1","type":"external","counters":"1","description":"see ip-forward.git"}}'
  apply=true
fi

if no_alias ip2tun; then
  opnsense-api firewall/alias/addItem/ '{"alias":{"name":"ip2tun","enabled":"1","type":"external","counters":"0","description":"see ip-forward.git"}}'
  apply=true
fi

if $apply; then
  r=`opnsense-api firewall/alias/reconfigure '{}'`
  r=`echo "$r" | jq -cr .status`
  test "$r" = ok
fi

########################################################################
# https://$(hostname)/ui/interfaces/vip

r=`opnsense-api interfaces/vip_settings/searchItem`
missing=`echo "$r" | jq -r '["127.4.5.1/32"] -  [.rows[].address] | .[]'`
if [ -n "$missing" ]; then
  opnsense-api interfaces/vip_settings/addItem '{"vip":{"mode":"ipalias","interface":"lo0","network":"127.4.5.1/32","nobind":"0","descr":"see ip-forward.git"}}'
  opnsense-api interfaces/vip_settings/reconfigure '{}'
fi

make -C /root/ip-forward install-unbound build install

########################################################################
# Services: Unbound DNS: General

unconf=`opnsense-api unbound/settings/get`

apply="{}"

# Otherwise it conflicts with 127.4.5.1
un_ifs=`echo "$unconf" | jq -r '[.unbound.general.active_interface | with_entries(.value.interface = .key) | .[] | select(.selected == 1) | .interface] | join(",")'`
if [ -z "$un_ifs" ]; then
  single_if=`opnsense-api interfaces/overview/interfacesInfo | jq -r '[.rows[] | select(.is_physical) | .identifier] as $ifs | if $ifs | length == 1 then $ifs[0] else [].[] end'`
  if [ -n "$single_if" ]; then
    apply=`jq -nc --argjson a "$apply" --arg i "$single_if" '$a | .active_interface = $i'`
  else
    wait4conf /opnsense/OPNsense/unboundplus/general/active_interface '<active_interface>.+</active_interface>'
  fi
fi

# To ease debugging.
cacheflush=`echo "$unconf" | jq -r '.unbound.general.cacheflush'`
if [ "$cacheflush" -ne 1 ]; then
  apply=`jq -nc --argjson a "$apply" '$a | .cacheflush = "1"'`
fi

if [ "$apply" != "{}" ]; then
  q=`jq -nc --argjson a "$apply" '{unbound:{general:$a}}'`
  opnsense-api unbound/settings/set "$q"
  opnsense-api unbound/service/reconfigureGeneral '{}'
fi

########################################################################
# Services: Unbound DNS: Advanced

apply="{}"

# To disable DNS rebinding protection for certain domains.
privatedomain=`jq -nc --argjson c "$unconf" '["mgmt.darkk.net.ru"] - [$c.unbound.advanced.privatedomain[].value]'`
if [ "$privatedomain" != "[]" ]; then
  apply=`jq -nc --argjson a "$apply" --argjson dl "$privatedomain" --argjson c "$unconf" '$a | .privatedomain = ([$c.unbound.advanced.privatedomain[].value] + $dl | join(","))'`
fi

# If infra flaps, it should be probbed despite of TTL.
infrakeepprobing=`jq -nr --argjson c "$unconf" '$c.unbound.advanced.infrakeepprobing'`
if [ "$infrakeepprobing" -ne 1 ]; then
  apply=`jq -nc --argjson a "$apply" '$a | .infrakeepprobing = "1"'`
fi

if [ "$apply" != "{}" ]; then
  q=`jq -nc --argjson a "$apply" '{unbound:{advanced:$a}}'`
  opnsense-api unbound/settings/set "$q"
  apply_base=true
else
  apply_base=false
fi

########################################################################
# Services: Unbound DNS: Query Forwarding

apply=${apply_base}

fwds=`jq -nr --argjson c "$unconf" '([$c.unbound.dots.dot[] | select(.domain == "" and .enabled == "1")] | length) + {"":0,"1":1}[$c.unbound.forwarding.enabled]'`
if [ "$fwds" -eq 0 -a -n "$single_if" ]; then
  # Router-on-a-stick is usually a poor recursor. Let's forward to DHCP and/or static upstream.
  opnsense-api unbound/settings/set '{"unbound":{"forwarding":{"enabled":"1"}}}'
  apply=true
fi

# To enable `do-not-query-localhost: no` in /var/unbound/etc/dot.conf template.
# Forwarding `vpn.works.` to 127.4.5.1 is a reasonable idea.
use127=`opnsense-api unbound/settings/searchForward | jq -r '[.rows[] | select(.server == "127.4.5.1")] | length'`
if [ "$use127" -eq 0 ]; then
  opnsense-api unbound/settings/addForward '{"dot":{"enabled":"1","domain":"vpn.works.","server":"127.4.5.1"}}'
  apply=true
fi

if $apply; then
  opnsense-api unbound/service/reconfigure '{}'
fi
