#!/bin/sh -ex

. b4ck.subr

ifinfo=`opnsense-api interfaces/overview/interfacesInfo`
hwifcnt=`jq -rn --argjson ifinfo "$ifinfo" '[$ifinfo.rows[] | select('"${IS_PHYSICAL}"')] | length'`
test "$hwifcnt" -eq 1 # This script is for Router-on-a-Stick for this moment.

########################################################################
# Gateway group VPNgwgrp

wait4conf '/opnsense/gateways/gateway_group[name/text()="VPNgwgrp" and trigger/text()="down"]' '</gateway_group>$'

########################################################################
# Firewall: NAT: Outbound. https://$(hostname)/firewall_nat_out.php

# First, we take care of the router itself. `pf` has no good way to NAT packets
# _after_ filter, and local packets do _NOT_ pass through any interface
# in _in_ direction (as far as I see). So, policy routing decision is
# essentially taking place in `nat` statement group for locally generated packets.

jsls=`ls -d ~/.opn*.json`
wgifs=`jq -r '.wggw[].if' $jsls`
if is_vrrp_assigned; then
  gwid=StickIfs
else # No VRRP, WANandOnly wins
  gwid=`jq -rn --argjson ifinfo "$ifinfo" '[$ifinfo.rows[] | select('"${IS_PHYSICAL}"')] | first | .identifier'`
fi
if2id=`jq -cn --argjson ifinfo "$ifinfo" '[$ifinfo.rows[] | {key: .description, value: .identifier}] | from_entries'`

for ifname in $wgifs; do
  id=`jq -rn --argjson id2id "$if2id" --arg ifname "$ifname" '$id2id[$ifname]'`
  : nat-n-tag
  wait4natout "interface/text()='${gwid}' and ipprotocol/text()='inet' and source/network/text()='(self)' and destination/network/text()='dns2tun' and target/text()='${id}ip' and staticnatport/text()='1' and tag/text()='via-${ifname}'"
  wait4natout "interface/text()='${gwid}' and ipprotocol/text()='inet' and source/network/text()='(self)' and destination/network/text()='ip2tun' and target/text()='${id}ip' and staticnatport/text()='1' and tag/text()='via-${ifname}'"
done

########################################################################
# Firewall: Rules: WANandOnly
#
# https://$(hostname)/firewall_rules.php?if=wan

gwinfo=`opnsense-api routing/settings/searchGateway`
for ifname in $wgifs; do
  gw=`jq -rn --argjson gwinfo "$gwinfo" --arg ifname "$ifname" '$gwinfo.rows[] | select(.interface_descr == $ifname and .ipprotocol == "inet" and .monitor_disable == "0") | .name'`
  : tag-n-route
  wait4filter "interface>${gwid}" 'direction>out' 'ipprotocol>inet' "gateway>${gw}" "tagged>via-${ifname}" 'statetype>keep state'
done

# Second, we take care of the forwarded traffic.
# #daily_OPNsense: note, it's destination/address/dns2tun, not destination/network/dns2tun ;-)
wait4filter_ "interface/text()='${gwid}' and direction/text()='in' and ipprotocol/text()='inet46' and protocol/text()='tcp/udp' and source/network/text()='${gwid}' and destination/network/text()='(self)' and port/text()='53'"
wait4filter_ "interface/text()='${gwid}' and direction/text()='in' and ipprotocol/text()='inet' and source/network/text()='${gwid}' and destination/address/text()='dns2tun' and gateway/text()='VPNgwgrp' and statetype='keep state'"
wait4filter_ "interface/text()='${gwid}' and direction/text()='in' and ipprotocol/text()='inet' and source/network/text()='${gwid}' and destination/address/text()='ip2tun' and gateway/text()='VPNgwgrp' and statetype='keep state'"
# The reason for sloppy-state being required both on `in` and `out` is not 100% clear to me, but it affects
# session lifetime.  https://speedtest.net shows 0.1 Mbit/s upload without direction>out rule.
# disablereplyto prevents replies to local packets (e.g. ICMP pongs) getting routed back to default gateway O_o
wait4filter_ "interface/text()='${gwid}' and direction/text()='in'  and ipprotocol/text()='inet' and source/network/text()='${gwid}' destination/not/text()='1' destination/network/text()='(self)' and statetype/text()='sloppy state' and disablereplyto/text()='1'"
wait4filter_ "interface/text()='${gwid}' and direction/text()='out' and ipprotocol/text()='inet' and source/network/text()='${gwid}' destination/not/text()='1' destination/network/text()='(self)' and statetype/text()='sloppy state' and disablereplyto/text()='1'"
